platform :ios,'8.0'
use_frameworks!
target "MonitoringPlatform" do 
	pod "AFNetworking"
    pod "ReactiveObjC"
    pod "MBProgressHUD"
    pod "SDWebImage"
    pod "MJExtension"
    pod "YLGIFImage"
end



